# Generated by Django 2.0.dev20170221005733 on 2017-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('dataset_author', models.CharField(max_length=200)),
                ('dataset_up_date', models.DateTimeField(verbose_name='Upload Date')),
                ('dataset_desc', models.TextField()),
                ('dataset_url', models.URLField(max_length=500)),
                ('dataset_file', models.FileField(upload_to='datasets/')),
            ],
        ),
    ]
