# Generated by Django 2.0.dev20170221005733 on 2017-03-10 05:34

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('model_author', models.CharField(max_length=200)),
                ('model_up_date', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 10, 5, 34, 57, 38564))),
                ('model_desc', models.TextField()),
                ('model_algo', models.CharField(max_length=200)),
                ('model_data_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_file',
            field=models.FileField(upload_to='datasets/', validators=[dashboard.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 10, 5, 34, 57, 30615)),
        ),
    ]
