# Generated by Django 2.0.dev20170221005733 on 2017-03-14 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170310_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 7, 23, 54, 837440)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_algo',
            field=models.CharField(choices=[('knn', 'K-NN'), ('svm', 'SVM'), ('nvb', 'Naive Bayes')], default='knn', max_length=200),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 7, 23, 54, 845293)),
        ),
    ]
