# Generated by Django 2.0.dev20170221005733 on 2017-03-14 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170314_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgoList',
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 7, 27, 25, 707748)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 7, 27, 25, 715565)),
        ),
    ]
