# Generated by Django 2.0.dev20170221005733 on 2017-03-14 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170314_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 8, 17, 2, 20919)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_algo',
            field=models.CharField(choices=[('knn', 'K-NN'), ('ann', 'Artificial Neural Networks'), ('nvb', 'Naive Bayes'), ('svm', 'SVM')], max_length=200),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 14, 8, 17, 2, 21504)),
        ),
    ]
