# Generated by Django 2.0.dev20170221005733 on 2017-03-21 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20170321_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 21, 7, 59, 24, 606915)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 21, 7, 59, 24, 607506)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 21, 7, 59, 24, 608411)),
        ),
    ]
