# Generated by Django 2.0.dev20170221005733 on 2017-03-21 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170321_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportInfo',
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 21, 8, 2, 47, 221898)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 21, 8, 2, 47, 222485)),
        ),
    ]
