# Generated by Django 2.0.dev20170221005733 on 2017-03-28 05:28

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170321_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_address', models.TextField()),
                ('user_address_city', models.CharField(max_length=200)),
                ('user_address_country', models.CharField(max_length=200)),
                ('user_address_pin', models.IntegerField()),
                ('user_desc', models.CharField(max_length=160)),
                ('user_profile_pic', models.FileField(upload_to='dashboard/media/userprofiles/', validators=[dashboard.validators.validate_user_dp_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 5, 28, 50, 46905)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 5, 28, 50, 47433)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 5, 28, 50, 48302)),
        ),
    ]
