# Generated by Django 2.0.dev20170221005733 on 2017-03-28 06:20

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170328_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 20, 27, 42519)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 20, 27, 43046)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 20, 27, 43892)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile_pic',
            field=models.FileField(upload_to='static/img/userprofiles/', validators=[dashboard.validators.validate_user_dp_extension]),
        ),
    ]
