# Generated by Django 2.0.dev20170221005733 on 2017-03-28 06:24

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20170328_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_company', models.CharField(max_length=200)),
                ('user_address', models.TextField()),
                ('user_address_city', models.CharField(max_length=200)),
                ('user_address_country', models.CharField(max_length=200)),
                ('user_address_pin', models.IntegerField()),
                ('user_desc', models.CharField(max_length=160)),
                ('user_profile_pic', models.FileField(upload_to='static/img/userprofiles/', validators=[dashboard.validators.validate_user_dp_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 24, 36, 583479)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 24, 36, 584009)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 6, 24, 36, 584935)),
        ),
    ]
