# Generated by Django 2.0.dev20170221005733 on 2017-03-28 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20170328_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 7, 1, 11, 320936)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 7, 1, 11, 321563)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 28, 7, 1, 11, 322510)),
        ),
    ]
