# Generated by Django 2.0.dev20170221005733 on 2017-04-10 07:57

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20170328_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='report_class_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='report_conf_matrix',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datainfo',
            name='dataset_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 7, 57, 56, 431028)),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 7, 57, 56, 431569)),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='report_up_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 10, 7, 57, 56, 432520)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile_pic',
            field=models.FileField(upload_to='dashboard/static/img/userprofiles/', validators=[dashboard.validators.validate_user_dp_extension]),
        ),
    ]
